### ISSUE TITLE
运行roslaunch unitree_lidar_ros run.launch，ARM架构报错

### ISSUE THREAD

**Issue by li1135759862** [unitreerobotics/unilidar_sdk#2]
terminate called after throwing an instance of 'serial::IOException'
  what():  IO Exception (5): Input/output error, file /home/pi/mlb_ws/unitree_lidar_sdk/src/serial/impl/unix.cc, line 151.

**Comment by li1135759862** [comment]
/home/pi/mlb_ws这个不是我本地的目录结构，源码中也没unitree_lidar_sdk/src/serial/impl/unix.cc这个文件

**Comment by lingbomeng** [comment]
可以看一下你的lidar串口设备名称是不是默认的`/dev/ttyUSB0`，如果不是在配置文件里修改成实际的名称。

**Comment by li1135759862** [comment]
串口是默认的，/dev/ttyUSB0
<img width="284" alt="image" src="https://github.com/unitreerobotics/unilidar_sdk/assets/30815149/e71ecb14-8fdf-4e9a-8272-0367e0f14fb3">

**Comment by li1135759862** [comment]
有没技术支持群？

**Comment by lingbomeng** [comment]
技术支持QQ群：861113138

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: li1135759862 ***@***.***>
发送时间: Monday, June 19, 2023 6:53:51 PM
收件人: unitreerobotics/unilidar_sdk ***@***.***>
抄送: Lingbo Meng ***@***.***>; Comment ***@***.***>
主题: Re: [unitreerobotics/unilidar_sdk] 运行roslaunch unitree_lidar_ros run.launch，ARM架构报错 (Issue #2)


有没技术支持群？

―
